# Generated by Django 2.2.12 on 2020-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(blank=True),
        ),
    ]
