# Generated by Django 2.2.12 on 2020-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200805_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(upload_to='media/sounds/'),
        ),
    ]
