# Generated by Django 2.2.12 on 2020-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20200805_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(upload_to='sounds/'),
        ),
    ]
